'use strict';
const fs=require('fs'); const assert=require('node:assert/strict');
const ws=fs.readFileSync('src/websocketHub.ts','utf8');
const cs=fs.readFileSync('src/commandService.ts','utf8');
let n=0; function pass(name){n++;console.log('PASS',name)} function has(t,r,name){assert.ok(r.test(t),name);pass(name)}
has(cs,/\["toggle",\s*"setOutputState",\s*"setPower",\s*"setBrightness"\]/,'toggle remains legacy output latest-wins member');
has(cs,/existing\.userId\s*===\s*input\.userId/,'durable duplicate ownership user-bound');
has(cs,/prisma\.\$transaction\(\[/,'durable latest-wins prepare transactional');
has(cs,/expiresAtEpochSec/,'numeric device expiry propagated');
has(ws,/body\.type === "liveCommand"[\s\S]*?body\.action !== "setOutputState"[\s\S]*?LIVE_ACTION_NOT_ALLOWED/,'liveCommand hard-restricted to ordered setOutputState');
has(ws,/private readonly durableInflight = new Map<string, DurableInflight>\(\)/,'durable inflight map');
has(ws,/durableInflight\.size >= WebSocketHub\.MAX_DURABLE_INFLIGHT[\s\S]*?return false/,'inflight capacity fails closed');
has(ws,/Promise\.resolve\(\)\.then\(\(\) =>\s*this\.sendCommandToBoundTarget/,'ownership installed before send microtask');
has(ws,/if \(existing\.terminalAckSeen\)[\s\S]*?return await existing\.sendPromise/,'terminal ACK blocks redispatch');
has(ws,/existing\.generation !== target\.generation[\s\S]*?this\.durableInflight\.delete\(key\)/,'unacked generation loss releases recovery ownership');
has(ws,/entry\.generation === generation && !entry\.terminalAckSeen/,'generation cleanup preserves terminal ACK tombstone');
has(ws,/markDurableInflightTerminalAck\(lampId, ack\.commandId, socket\.meta!\.generation!\)/,'ACK terminal marker bound to socket generation');
has(ws,/releaseDurableInflight\(lampId, ack\.commandId, socket\.meta!\.generation!\)/,'ACK tombstone released after DB visibility');
has(ws,/Keep the in-memory terminal ACK tombstone until command expiry if DB[\s\S]*?Releasing here would reopen duplicate redispatch/,'DB failure preserves ACK tombstone');
has(ws,/sendDurableCommandToBoundTarget\(lampId, target, \{/,'reconnect flush goes through durable guard');
has(ws,/sendDurableCommandToBoundTarget\(command\.device\.lampId, retryTarget, \{/,'requestState retry goes through durable guard');
has(ws,/DEVICE_SEND_CALLBACK_BUDGET_MS = 300/,'device send callback budget bounded');
has(ws,/socket\.bufferedAmount > MAX_SOCKET_BUFFERED_BYTES/,'socket backpressure bounded');
has(ws,/MAX_DEVICE_COMMAND_FRAME_BYTES = 511[\s\S]*?frameBytes > MAX_DEVICE_COMMAND_FRAME_BYTES[\s\S]*?return false/,'device command frame bounded to ESP RX capacity');
has(ws,/pendingStatePersistence/,'state persistence bounded latest-slot architecture');
has(ws,/deviceMessageChains/,'device inbound chain generation-scoped');
has(ws,/this\.deviceSockets\.get\(lampId\) !== socket/,'authoritative generation checked before device send');
has(ws,/if \(this\.deviceSockets\.get\(lampId\) === socket\)[\s\S]*?online: false/,'stale device socket cannot publish offline');
has(ws,/action: "requestState"/,'backend retry limited to requestState query');
const af=ws.indexOf('CMD ack_forward'); const db=ws.indexOf('prisma.deviceCommand.updateMany({',af); assert.ok(af>=0&&db>af);pass('ACK forwarded before status persistence');
console.log(`RF5.4.2 deep source contracts: ALL PASS count=${n}`);
